---
# tasks file for nexus

#- name: install java
 # yum: 
  #  name: java-1.8.0-openjdk.x86_64
   # state: installed

# - name: create "nexus" group
#   group: name=nexus 

# - name: create "nexus" user
#   user: name=nexus group=nexus

# - name: create /tmp/nexus/3 directory
#   file: path=/tmp/nexus/3 state=directory

# - name: install nexus
#   become: yes
#   get_url:
#        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
#        dest: /tmp/nexus/3/bundle.tar.gz

# - name: create /tmp/nexus_dir directory
#   file: path=/tmp/nexus_dir state=directory

- name: extract nexus to /tmp/nexus_dir
  unarchive:
    src: /tmp/nexus/3/bundle.tar.gz
    dest: /tmp/nexus_dir/
    remote_src: yes


- name: make /usr/local/nexus directory property of "nexus" user/group
  file: path=/usr/local/nexus group=nexus owner=nexus recurse=true
  
# - name: move nexus to /tmp/nexus_extracted_dir directory
#   command: cp -a /tmp/nexus_dir . /usr/local/nexus
# - name: Copy file with owner and permissions
#   copy:
#     src: /tmp/nexus_dir
#     dest: /usr/local/nexus
#     remote_src: yes

# - name: make nexus runned by "nexus" user
#   lineinfile: dest=/usr/local/nexus/nexus-3.22.0-02/bin/nexus regexp="#RUN_AS_USER=" line="RUN_AS_USER=nexus" backrefs=true
    
# - name: set NEXUS_HOME
#   lineinfile: dest=/usr/local/nexus/nexus-3.22.0-02/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME=/usr/local/nexus" backrefs=true
# - name: set NEXUS_HOME
#   lineinfile: dest=/usr/local/nexus/nexus-3.22.0-02/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME=/usr/local/nexus/nexus-3.22.0-02" backrefs=true
  

# - name: create nexus piddir
#   file: path=/var/run/nexus state=directory group=nexus owner=nexus
  

# - name: set nexus pidir
#   lineinfile: dest=/usr/local/nexus/nexus-3.22.0-02/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true


# - name: create symbolic links to /etc/init.d/nexus
#   file: src=/usr/local/nexus/nexus-3.22.0-02/bin/nexus dest=/etc/init.d/nexus state=link
# - name: create nexus piddir
#   file: path=/etc/systemd/system/nexus.service

# - name: set nexus pidir
#   lineinfile: dest=/usr/local/nexus/nexus-3.22.0-02/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true

- name: create nexus piddir
  file: path=/etc/systemd/system state=directory 
- name: create nexus 
  file: path=/etc/systemd/system/nexus.service state=file

- name: Upload default index.html for host
  copy: src="/home/mohamed/ans/f1" dest="/etc/systemd/system/nexus.service" mode=0644

- name: start nexus
  become: yes
  service: 
    name: nexus
    state: started